CREATE DATABASE langxin_community character set utf8;

use langxin_community;

CREATE TABLE residents (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `街道` VARCHAR(20),
    `社区` VARCHAR(20),
    `网格` VARCHAR(20),
    `小区` VARCHAR(20),
    `所居住花园小区/城中村名称` VARCHAR(40),
    `所属电子哨兵卡口名称` VARCHAR(100),
    `姓名` VARCHAR(100),
    `性别` VARCHAR(3),
    `人员类型` VARCHAR(20),
    `证件类型` VARCHAR(20),
    `证件号码` VARCHAR(1000),
    `出生年月` DATETIME,
    `手机号码` VARCHAR(20),
    `国籍` VARCHAR(20),
    `是否暂离` VARCHAR(20),
    `户籍地址` VARCHAR(100),
    `工作单位所在市` VARCHAR(20),
    `工作单位所在行政区` VARCHAR(20),
    `工作单位名称` VARCHAR(40),
    `工作单位地址` VARCHAR(100),
    `是否纳入市网格办统计` VARCHAR(20),
    `楼栋地址` VARCHAR(100),
    `楼栋编码` VARCHAR(25),
    `房屋地址` VARCHAR(100),
    `房屋编码` VARCHAR(25),
    `备注` VARCHAR(100),
    `审核结果` VARCHAR(20),
    `审核人` VARCHAR(20),
    `审核时间` DATETIME,
    `上报类型` VARCHAR(20),
    `是否在白名单` VARCHAR(2) DEFAULT '是',
    `是否在灰名单` VARCHAR(2) DEFAULT '否',
    `灰名单类型` INT,
    `灰名单原因` VARCHAR(100),
    `上次核酸检测时间` DATETIME,
    `加入白名单时间` DATETIME,
    `移出白名单时间` DATETIME,
    PRIMARY KEY (`id`),
    INDEX idx_rid(`证件号码`),
    INDEX idx_insert_time(`审核时间`),
    INDEX idx_remove_time(`移出白名单时间`),
    INDEX idx_location(`房屋地址`)
) DEFAULT CHARSET=utf8;

CREATE TABLE covid_detection_records (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `姓名` VARCHAR(100),
    `出生日期` DATE,
    `年龄` INT,
    `电话号码` VARCHAR(20),
    `机构所在地` VARCHAR(100),
    `采样机构` VARCHAR(40),
    `采样时间` DATETIME,
    `检测机构` VARCHAR(40),
    `检测时间` DATETIME,
    `检测结果` VARCHAR(20),
    `检测结果填报时间` DATETIME,
    `复核结果` VARCHAR(20),
    `复核机构` VARCHAR(40),
    `复核时间` DATETIME,
    `性别` VARCHAR(20),
    `国家/地区` VARCHAR(20),
    `居住地` VARCHAR(100),
    `证件类型` VARCHAR(20),
    `证件号码` VARCHAR(40),
    `未提供有效证件原因` VARCHAR(100),
    `检测人群分类` VARCHAR(40),
    `应检尽检类别` VARCHAR(40),
    `导入机构` VARCHAR(40),
    `样本条形码` VARCHAR(25),
    `样本类型` VARCHAR(20),
    `检测项目` VARCHAR(20),
    `采样点行政区划` VARCHAR(100),
    `采样地点` VARCHAR(100),
    `所在学校/单位名称` VARCHAR(40),
    `备注1` VARCHAR(100),
    `备注2` VARCHAR(100),
    `采集类型` VARCHAR(20),
    `导入时间` DATETIME,
    `创建人账号` VARCHAR(20),
    `创建人姓名` VARCHAR(40),
    PRIMARY KEY (`id`),
    INDEX idx_rid(`证件号码`),
    INDEX idx_sample_time(`采样时间`)
) DEFAULT CHARSET=utf8;
